sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: 10.175.94.226
    port: 3306
    database: sky_take_out
    username: remote
    password: '1024.'

  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${ALI_OSS_ACCESS_KEY_ID}
    access-key-secret: ${ALI_OSS_ACCESS_KEY_SECRET}
    bucket-name: java-ai-genhaosan
  redis:
    host: 10.175.94.226
    port: 6379
    password: '1024.'
    database: 10

  wechat:
    appid: wx9c62dde540ef7f7d
    secret: 64d42368b155f121442af2a288037a59